export default function () {

	var id = 0;

	var data = [
		{
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 400,
			"power saving mode": true,
			"egg tray": false,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Double Door",
			"capacity": "250",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 52,
			"color": "Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2015,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": false,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Blue",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consmption": 400,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 52,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": false,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "250",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": false,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2015,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Blue",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 400,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Single Door",
			"capacity": "250",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 52,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": false,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Gray",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consmption": 600,
			"power saving mode": false,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "250",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2016,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 400,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 52,
			"color": "Blue",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "250",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": false,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": false,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2016,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 400,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 72,
			"color": "Blue",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "250",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Maroon",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 500,
			"power saving mode": true,
			"egg tray": false,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2015,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 72,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Maroon",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consmption": 600,
			"power saving mode": false,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "250",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2016,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 500,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 72,
			"color": "Maroon",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": false,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2016,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "250",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Maroon",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 500,
			"power saving mode": false,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2015,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 72,
			"color": "Maroon",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": false,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "250",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 500,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2015,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": false,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Maroon",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "250",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 72,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": false,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 5,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consmption": 500,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2016,
			"warranty": 2,
			"handle type": "Ariana",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": false,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "250",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Maroon",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Double Door",
			"capacity": "192",
			"price": 50000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2017,
			"warranty": 5,
			"handle type": "Ariana",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 36,
			"color": "Blue",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consmption": 600,
			"power saving mode": true,
			"egg tray": true,
		}, {
			"compressor type": "Reciprocatory Compressor",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": false,
			"manufacture year": 2017,
			"warranty": 2,
			"handle type": "Chrome",
			"net height": 1192,
			"net depth": 649,
			"net width": 532,
			"weight": 72,
			"color": "Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 500,
			"power saving mode": false,
			"egg tray": false,
		}, {
			"compressor type": "Smart Inverter",
			"type": "Single Door",
			"capacity": "192",
			"price": 30000,
			"star rating": "3",
			"built-in stabilizer": true,
			"manufacture year": 2016,
			"warranty": 5,
			"handle type": "Ariana",
			"net height": 1372,
			"net depth": 746,
			"net width": 623,
			"weight": 36,
			"color": "Blue",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consmption": 600,
			"power saving mode": false,
			"egg tray": true,
		}
	];

	data.forEach(function (value) {

		value.id = ++id;
	});

	return data;
}
