export default function () {

	var id = 0;

	var data = [
		{
			"category": "Smart",
			"type": "LED TV",
			"screen size": "32 inch (80 cm)",
			"price": 30000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Black",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "32 inch (80 cm)",
			"price": 25000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Dark Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Black",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "55 inch (139 cm)",
			"price": 55000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Dark Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "84 inch (213 cm)",
			"price": 75000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD**",
			"weight": 6.7,
			"color": "Black",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Dark Gray",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "55 inch (139 cm)",
			"price": 60000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Black",
			"model": "Samsung32J5500AK",
			"brand": "Samsung",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "84 inch (213 cm)",
			"price": 65000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.7,
			"color": "Gray",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Dark Gray",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "32 inch (80 cm)",
			"price": 30000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Black",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "55 inch (139 cm)",
			"price": 50000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Dark Gray",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Gray",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "84 inch (213 cm)",
			"price": 75000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD**",
			"weight": 6.7,
			"color": "Black",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Gray",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "55 inch (139 cm)",
			"price": 60000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Black",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "84 inch (213 cm)",
			"price": 65000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.7,
			"color": "Dark Gray",
			"model": "LG32J5500AK",
			"brand": "LG",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Gray",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "32 inch (80 cm)",
			"price": 30000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Black",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "84 inch (213 cm)",
			"price": 65000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.7,
			"color": "Dark Gray",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Gray",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "55 inch (139 cm)",
			"price": 60000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Black",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "84 inch (213 cm)",
			"price": 70000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD*",
			"weight": 6.7,
			"color": "Gray",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 45000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Black",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "55 inch (139 cm)",
			"price": 55000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Gray",
			"model": "Sony32J5500AK",
			"brand": "Sony",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 45000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Black",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "84 inch (213 cm)",
			"price": 70000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD*",
			"weight": 6.7,
			"color": "Gray",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "32 inch (80 cm)",
			"price": 30000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Black",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "43 inch (109.22 cm)",
			"price": 35000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Dark Gray",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "55 inch (139 cm)",
			"price": 55000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Gray",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "32 inch (80 cm)",
			"price": 30000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Black",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "84 inch (213 cm)",
			"price": 65000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.7,
			"color": "Dark Gray",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Gray",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "32 inch (80 cm)",
			"price": 30000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Black",
			"model": "Pana32J5500AK",
			"brand": "Panasonic",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "55 inch (139 cm)",
			"price": 50000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Dark Gray",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "32 inch (80 cm)",
			"price": 25000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Gray",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 45000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Black",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "84 inch (213 cm)",
			"price": 65000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.7,
			"color": "Dark Gray",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "32 inch (80 cm)",
			"price": 25000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Gray",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "55 inch (139 cm)",
			"price": 60000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Black",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "43 inch (109.22 cm)",
			"price": 35000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Dark Gray",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "32 inch (80 cm)",
			"price": 25000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Gray",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "84 inch (213 cm)",
			"price": 75000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD**",
			"weight": 6.7,
			"color": "Black",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "Sansui32J5500AK",
			"brand": "Sansui",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Gray",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "55 inch (139 cm)",
			"price": 60000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Black",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Gray",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "84 inch (213 cm)",
			"price": 75000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD**",
			"weight": 6.7,
			"color": "Black",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "55 inch (139 cm)",
			"price": 55000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Gray",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 45000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Black",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "84 inch (213 cm)",
			"price": 70000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD*",
			"weight": 6.7,
			"color": "Gray",
			"model": "Micro32J5500AK",
			"brand": "Micromax",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 45000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Black",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "55 inch (139 cm)",
			"price": 55000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Gray",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Android",
			"type": "LED TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 45000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Black",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Smart",
			"type": "Flat Screen",
			"screen size": "32 inch (80 cm)",
			"price": 20000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 1,
				"HDMI ports": 2,
				"internet": false,
			},
			"HD": "Half HD",
			"weight": 4.6,
			"color": "Dark Gray",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "84 inch (213 cm)",
			"price": 70000,
			"screen resolution": "3840 x 2160 (4K)",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 3,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD*",
			"weight": 6.7,
			"color": "Gray",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 200,
			"power saving mode": true,
			"speakers": 4,
		}, {
			"category": "Smart",
			"type": "LED TV",
			"screen size": "32 inch (80 cm)",
			"price": 30000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 2,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 4.6,
			"color": "Black",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 90,
			"power saving mode": true,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "Flat Screen",
			"screen size": "55 inch (139 cm)",
			"price": 50000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Dark Gray",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}, {
			"category": "Smart",
			"type": "LCD TV",
			"screen size": "43 inch (109.22 cm)",
			"price": 40000,
			"screen resolution": "1920 x 1080",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 5.2,
			"color": "Gray",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 120,
			"power saving mode": false,
			"speakers": 2,
		}, {
			"category": "Android",
			"type": "LCD TV",
			"screen size": "55 inch (139 cm)",
			"price": 55000,
			"screen resolution": "1366 x 768",
			"aspect ratio": "16:9",
			"supported audio formats": [
				"MP3", "AAC", "WMA", "PCM"
			],
			"connectivity": {
				"USB ports": 2,
				"HDMI ports": 3,
				"internet": true,
			},
			"HD": "Full HD",
			"weight": 6.0,
			"color": "Black",
			"model": "PHILIPS32J55AK",
			"brand": "Philips",
			"power consumption": 150,
			"power saving mode": true,
			"speakers": 3,
		}
	];

	data.forEach(function (value) {

		value.id = ++id;
	});

	return data;
}
